### ISSUE TITLE
2ndUserOwner issue ping1

### ISSUE THREAD

**Issue by DipakQa2** [DipakQa2/2ndUserSample1#1]
O1

**Comment by dipak-demansol** [comment]
d1 adding comment

**Comment by dipak-demansol** [comment]
d1 adding comment 2

**Comment by dipak-demansol** [comment]
ram

**Comment by dipak-demansol** [comment]
ramji

**Comment by DipakQa2** [comment]
owner adding the comment lets see dipak1 is getting the noti or not

**Comment by dipakQa3** [comment]
2nd user is owner, 3rd user is adding the comment and issue is assignned to me (Dipak1) so when 3rd user is adding the comment so the 1st and 2nd user should get the noti because its a 2nd user issue and 1st user is assigned that why 1st user will get the noti.

**Comment by dipak-demansol** [comment]
i comment

**Comment by DipakQa2** [comment]
2nd user comment

**Comment by dipakQa3** [comment]
3rd user comment
